server:
  port: 8888

spring:
  application:
    name: microservice-config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ErnestoAlfonso/WasteProject
        native:
          search-locations: classpath:/configurations