server:
  port: 8092

spring:
  application:
    name: msvc-wastea
  datasource:
    url: jdbc:h2:mem:wasteauthorizationdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka